// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static partial class NativeMethods
    {
        const string __DllName = "../../../../../../rust/target/debug/libtest_autobind.so";



        /// <summary>
        ///  Adds two integers together.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int add(int a, int b);

        /// <summary>
        ///  Prints a string to the console. This is present to make sure
        ///  that the slightly more complex handling of C-Strings between
        ///  the two environments is happy.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "print", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void print(string text);


    }



}