[package]
name = "batch_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
lancedb = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
